@startuml
actor User
participant ":GroupCommand" as GroupCommand
participant ":Group" as Group
participant ":User" as NewUser

User -> GroupCommand: "member USER_NAME"
activate GroupCommand

GroupCommand -> Group: addMember(memberName)
activate Group

alt is valid member name
    alt is not a member

        Group -> NewUser: new User(memberName)
        activate NewUser
        NewUser --> Group: newUser
        deactivate NewUser

        Group --> GroupCommand: success message
    else is already a member

        Group --> GroupCommand: failure message
    end
else is invalid member name

    Group --> GroupCommand: failure message
    deactivate Group
end

GroupCommand --> User: command result
deactivate GroupCommand
@enduml