@startuml
actor User
participant ":GroupCommand" as GroupCommand
participant ":Group" as Group
participant ":GroupStorage" as GroupStorage
participant ":FileIO" as FileIO

User -> GroupCommand: "exit Project Team"
activate GroupCommand

GroupCommand -> Group: exitGroup("Project Team")
activate Group

Group -> GroupStorage: saveGroupToFile(projectTeamGroup)
activate GroupStorage

GroupStorage -> FileIO: getFileWriter(filePath)
activate FileIO
FileIO --> GroupStorage: writer
deactivate FileIO

GroupStorage -> GroupStorage: saveGroupName(writer, groupName)
activate GroupStorage
deactivate GroupStorage

GroupStorage -> GroupStorage: saveMembers(writer, members)
activate GroupStorage
deactivate GroupStorage

GroupStorage -> GroupStorage: saveExpenses(writer, expenses)
activate GroupStorage
deactivate GroupStorage

GroupStorage -> FileIO: writer.close()
activate FileIO
FileIO --> GroupStorage
deactivate FileIO

GroupStorage --> Group
deactivate GroupStorage

Group --> GroupCommand
deactivate Group

GroupCommand --> User
deactivate GroupCommand
@enduml