@startuml
actor User
participant ":GroupCommand" as GroupCommand
participant ":Group" as Group
participant ":GroupStorage" as GroupStorage
participant ":FileIO" as FileIO

User -> GroupCommand: "enter Project Team"
activate GroupCommand

GroupCommand -> Group: enterGroup("Project Team")
activate Group

alt group does not exist in memory

    alt group file exists

        Group -> GroupStorage: loadGroupFromFile("Project Team")
        activate GroupStorage

        GroupStorage -> FileIO: getFileReader(filePath)
        activate FileIO
        FileIO --> GroupStorage: reader
        deactivate FileIO

        GroupStorage -> GroupStorage: loadGroupName(reader)
        activate GroupStorage
        deactivate GroupStorage

        GroupStorage -> GroupStorage: loadMembers(reader, group)
        activate GroupStorage
        deactivate GroupStorage

        GroupStorage -> GroupStorage: loadExpenses(reader, group)
        activate GroupStorage
        deactivate GroupStorage

        GroupStorage -> FileIO: reader.close()
        activate FileIO
        FileIO --> GroupStorage
        deactivate FileIO

        GroupStorage --> Group: loadedGroup
        deactivate GroupStorage
    else group file does not exist

        Group --> GroupCommand: group does not exist
    end
else group exists in memory

    Group --> GroupCommand: group found in memory
    deactivate Group
end

GroupCommand --> User
deactivate GroupCommand
@enduml